name: Package Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: ${{ github.ref != 'refs/heads/main' && 'https://npm.pkg.github.com/' || 'https://registry.npmjs.org/' }}
        scope: '@principlestudios'

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install node modules
      run: npm ci

    ###########
    # TEST
    - name: Run typecheck
      run: npm run typecheck

    - name: Run linter
      run: npm run lint -- --max-warnings 0

    - name: Test package
      env:
        CI: "true"
      run: npm test -- --passWithNoTests

    ###########
    # PACK
    - name: Pack npm package
      run: npm pack

    ###########
    # PUBLISH
    - name: Set publish NPM registry
      if: ${{ github.ref == 'refs/heads/main' }}
      run:  |
        echo '@principlestudios:registry=$NODE_REGISTRY' > ~/.npmrc
      env:
        NODE_REGISTRY: ${{ github.ref != 'refs/heads/main' && 'https://npm.pkg.github.com/' || 'https://registry.npmjs.org/' }}

    - name: Publish npm package
      run:  |
        if [[ $IS_PRERELEASE ]]; then npm --no-git-tag-version version prerelease --preid=branch.$IS_PRERELEASE; fi
        npm publish || echo 'npm publish optional'
      continue-on-error: true # npm publish does not have a `--skip-duplicate` switch
      env:
        IS_PRERELEASE: ${{ github.ref != 'refs/heads/main' && github.sha || '' }}
        NODE_AUTH_TOKEN: "${{ github.ref == 'refs/heads/main' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}"